# Generated by Django 4.1.2 on 2022-11-04 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FollowappUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=70, unique=True)),
                (
                    "questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "followers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "following",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        size=None,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_super_user", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField()),
                ("date_joined", models.DateTimeField()),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
