# Generated by Django 4.1.2 on 2022-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClickverseUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=70, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_super_user", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField()),
                ("date_joined", models.DateTimeField()),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ClickverseUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=100)),
                ("teamleads_user_id", models.IntegerField()),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserHasGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField(unique=True)),
                ("user_id", models.IntegerField()),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
